name: Scheme Engine CI

on:
  push:
    branches:
      - main

jobs:
  scheme-engine-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node 16.x
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Install
        run: npm ci
      - name: Compile Grammar
        run: npm run compile:grammar
      - name: Run Tests
        run: npm test
      - name: Run CLI Option 1
        run: npm run scheme -- -f ci/example
      - name: Run CLI Option 2
        run: echo \'turkey | npm run scheme -- -i
      - name: Run CLI Option 3
        run: echo ci/example | npm run scheme -- -i -f
